services:
  caddy:
    image: bibica/caddy-dns-cloudflare
    container_name: caddy
    restart: always
    networks:
      reverse_proxy:
        ipv4_address: 172.18.0.2
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    environment:
      - CLOUDFLARE_API_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXX
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    logging:
      driver: "none"
      
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    networks:
      reverse_proxy:
        ipv4_address: 172.18.0.3
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/config:/opt/adguardhome/conf
    logging:
      driver: "none"

networks:
  reverse_proxy:
    driver: bridge
    name: reverse_proxy
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
