services:
  caddy:
    image: caddy:2.10.2-alpine
    container_name: caddy
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - ./domain-config:/domain-config
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    logging:
      driver: "none"

  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    restart: always
    networks:
      - reverse_proxy
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/config:/opt/adguardhome/conf
      - ./caddy_data:/caddy_data:ro
    logging:
      driver: "none"

networks:
  reverse_proxy:
    driver: "bridge"
    name: reverse_proxy
